# Generated by Django 4.1.7 on 2023-03-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article_image', models.ImageField(blank=True, upload_to='images/')),
                ('article_range', models.IntegerField(choices=[(0, '0 months'), (1, '1 months'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (5, '6 months'), (7, '7 months'), (8, '8 months'), (9, '9 months'), (10, '10 months'), (11, '11 months'), (12, '12 months')])),
            ],
        ),
    ]
