# Generated by Django 4.1.7 on 2023-03-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_children',
        ),
    ]
